-- Full real product list (55 items). Run this AFTER schema.sql
delete from products;
insert into products (name, variant, price, cost) values
('Alice Dainty Initial Necklace','',22.0,1.0),
('Amelia Duo Huggies','',20.0,1.8),
('Ann Skinny Name Ring in 18K Gold','',22.0,1.4),
('Baguette Birthstone Bracelet','',19.0,2.6),
('Baguette Birthstone Ring','',20.0,1.4),
('Butterfly Drop Huggies','',15.0,1.2),
('Butterfly Drop Necklace in 18K Gold','',18.0,1.3),
('Classic Diamond Tennis Bracelet in 18K Gold','',27.0,4.0),
('Classic Diamond Tennis Bracelet in Silver','',27.0,4.0),
('Dainty Diamond Necklace','',18.0,1.5),
('Dainty Diamond Tennis Necklace & Bracelet Set in 18K Gold','',49.99,9.6),
('Dainty Diamond Tennis Necklace & Bracelet Set in Silver','',49.99,9.6),
('Diamond Flatback Studs Set','A. Small - 2mm',12.0,0.65),
('Diamond Flatback Studs Set','B. Medium - 2.5mm',15.0,0.7),
('Diamond Flatback Studs Set','C. Large - 3mm',18.0,0.75),
('Diamond Flatback Studs Set','D. Set of 3: Studs (Save 30%)',30.0,2.1),
('Diamond Tennis Choker Necklace in Gold','',30.0,5.6),
('Diamond Tennis Choker Necklace in Silver','',30.0,5.6),
('Diamond Tennis Clasp Necklace in 18K Gold','',32.0,6.2),
('Duo Pear Toi Et Moi Ring in 18K Gold','gold',23.0,2.4),
('Emery Birthstone Necklace','',22.0,3.0),
('Eternity Birthstone Ring','',20.0,1.25),
('Klara Tennis Bracelet','',25.0,4.6),
('Mariposa Diamond Ring','',22.0,0.9),
('Marquise Diamond Necklace in 18K Gold','',18.0,2.5),
('Morse Code Necklace','',29.99,2.0),
('Opal Inlay Huggies Set','18-k-gold  /  A. Milky White',20.0,3.8),
('Opal Inlay Huggies Set','18-k-gold  /  B. Deep Blue',20.0,3.8),
('Opal Inlay Huggies Set','18-k-gold  /  C. Garden Green',20.0,3.8),
('Opal Inlay Huggies Set','18-k-gold  /  Set of 3: White + Blue + Green Huggies',80.0,12.0),
('Ophelia Birthstone Necklace','',24.0,1.8),
('Sideways Initial Birthstone Bracelet','1 Birthstone  /  1 Initial',25.0,2.0),
('Sideways Initial Birthstone Bracelet','1 Birthstone  /  2 Initial  (+ $3)',28.0,2.4),
('Sideways Initial Birthstone Bracelet','1 Birthstone  /  3 Initial  (+ $6)',31.0,2.8),
('Sideways Initial Birthstone Bracelet','2 Birthstones (+ $3)  /  1 Initial',28.0,2.4),
('Sideways Initial Birthstone Bracelet','2 Birthstones (+ $3)  /  2 Initial  (+ $3)',31.0,2.8),
('Sideways Initial Birthstone Bracelet','2 Birthstones (+ $3)  /  3 Initial  (+ $6)',34.0,3.2),
('Sideways Initial Birthstone Bracelet','3 Birthstones (+ $6)  /  1 Initial',31.0,3.4),
('Sideways Initial Birthstone Bracelet','3 Birthstones (+ $6)  /  2 Initial  (+ $3)',34.0,3.8),
('Sideways Initial Birthstone Bracelet','3 Birthstones (+ $6)  /  3 Initial  (+ $6)',37.0,4.2),
('Sideways Initial Birthstone Necklace','1 Birthstone  /  1 Initial',28.0,2.0),
('Sideways Initial Birthstone Necklace','1 Birthstone  /  2 Initial  (+ $3)',31.0,2.4),
('Sideways Initial Birthstone Necklace','1 Birthstone  /  3 Initial  (+ $6)',34.0,2.8),
('Sideways Initial Birthstone Necklace','2 Birthstones (+ $3)  /  1 Initial',31.0,2.4),
('Sideways Initial Birthstone Necklace','2 Birthstones (+ $3)  /  2 Initial  (+ $3)',34.0,2.8),
('Sideways Initial Birthstone Necklace','2 Birthstones (+ $3)  /  3 Initial  (+ $6)',37.0,3.2),
('Sideways Initial Birthstone Necklace','3 Birthstones (+ $6)  /  1 Initial',34.0,3.4),
('Sideways Initial Birthstone Necklace','3 Birthstones (+ $6)  /  2 Initial  (+ $3)',37.0,3.8),
('Sideways Initial Birthstone Necklace','3 Birthstones (+ $6)  /  3 Initial  (+ $6)',40.0,4.2),
('Sideways Initial Necklace','',24.0,1.0),
('Signature Name and Birthstone Necklace','',38.0,7.0),
('Toi et Moi Birthstone Bracelet','',25.0,2.0),
('Toi et Moi Birthstone Necklace','',27.0,2.4),
('Toi et Moi Teardrop Heart Bracelet','gold',25.0,1.5),
('Toi et Moi Teardrop Heart Necklace','gold',27.0,1.7);
